---
upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sales
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sensor_stock_levels
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sensor_storage_temperature

cleaned-upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sales_agg
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: stock_level_agg
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: df_stock_temp_agg

final_cleaned_python_sql:
  export:
    - export:
        host: s3
        bucket: ds-project-demo1
        filename: processed_data

Model_building:
  export:
    - export:
        host: s3
        bucket: end2enddsproject
        filename2: ml_output

modeling_final:
  export:
    - export:
        host: gsheet
        spread_sheet_id: 1mHw-uzkqThGeNJvnJt6L1fcwTddBc5cJ5Xo0ib5gdHk
        worksheet_name: Sheet1